{
 "title": "DnsCollector Loki",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" },
   { "name": "domain", "label": "Domain Name" },
   { "name": "ip", "label": "Query IP" },
   { "name": "custom", "label": "Custom Search" }
  ]
 },
 "panels": [
  { "title": "Frequency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate( ({job=\"$job\"} |~ \"$domain\" |~ \"$ip\" |~ \"$custom\")[5s] )"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$job\"} |= \"$domain\" |= \"$ip\" |= \"$custom\" [$__range]))"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "DNS Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 22, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"$job\"} |~ \"$domain\" |~ \"$ip\" |~ \"$custom\""
    }
   ]
  },
  { "title": "Top", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Top Domain Names",
   "type": "table",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(15, sum(count_over_time( ({job=\"$job\"} | pattern \"<_> <_> <_> <_> <_> <_> <_> <qname> <_> <_>\" |~ \"$domain\" |~ \"$ip\" |~ \"$custom\" )[$__range]  )) by (qname))"
    }
   ]
  },
  {
   "title": "Top IP",
   "type": "table",
   "gridPos": { "h": 16, "w": 11, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(15, sum(count_over_time( ({job=\"$job\"} | pattern \"<_> <_> <_> <_> <queryip> <_> <_> <_> <_> <_>\" |~ \"$domain\" |~ \"$ip\" |~ \"$custom\" )[$__range]  )) by (queryip))"
    }
   ]
  }
 ]
}