{
 "title": "DnsCollector Prometheus - Basic",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prom_prefix", "query": "${VAR_PROM_PREFIX}" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "stream_id",
    "label": "Stream",
    "query": {
     "query": "label_values({job=\"$job\"},stream_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Streams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (${prom_prefix}_throughput_ops{job=~\"$job\", stream_id=~\"$stream_id\"})",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Clients IP",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(${prom_prefix}_requesters_count{job=~\"$job\", stream_id=~\"$stream_id\"})",
     "legendFormat": "Total "
    }
   ]
  },
  {
   "title": "Domains",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (${prom_prefix}_domains_count{job=~\"$job\", stream_id=~\"$stream_id\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum (${prom_prefix}_domains_nx_count{job=~\"$job\", stream_id=~\"$stream_id\"} *100) ) / sum (${prom_prefix}_domains_count{job=~\"$job\", stream_id=~\"$stream_id\"}) ",
     "legendFormat": "Non-Existents"
    }
   ]
  },
  {
   "title": "Total Packets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\"}[1h])) ",
     "legendFormat": "Last hour"
    },
    {
     "expr": "sum(increase(${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\"}[24h]))",
     "legendFormat": "Last 24hr"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(${prom_prefix}_received_bytes_total{job=~\"$job\", stream_id=~\"$stream_id\"}[1h])) + sum(increase(${prom_prefix}_sent_bytes_total{job=~\"$job\", stream_id=~\"$stream_id\"}[1h])) ",
     "legendFormat": "Last hour"
    },
    {
     "expr": "sum(increase(${prom_prefix}_received_bytes_total{job=~\"$job\",stream_id=~\"$stream_id\"}[24h])) + sum(increase(${prom_prefix}_sent_bytes_total{job=~\"$job\", stream_id=~\"$stream_id\"}[24h]))",
     "legendFormat": "Last 24hr"
    }
   ]
  },
  {
   "title": "Network Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(net_transport) (${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\"} )*100 / ignoring(net_transport) group_left sum (${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\"})",
     "legendFormat": "{{ net_transport }}"
    }
   ]
  },
  {
   "title": "DNS Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3,sum by(query_type) (${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\"} )*100 / ignoring(query_type) group_left sum (${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\"}))",
     "legendFormat": "{{ query_type }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (${prom_prefix}_throughput_ops_max{job=~\"$job\", stream_id=~\"$stream_id\"})",
     "legendFormat": "Max OPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\"}) by (stream_id))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(net_family) (${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\"} )*100 / ignoring(net_family) group_left sum (${prom_prefix}_packets_count{job=~\"$job\",stream_id=~\"$stream_id\"})",
     "legendFormat": "{{ net_family }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\", return_code=\"NOERROR\"}) )*100 / sum(${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\"}) ",
     "legendFormat": "NOERROR"
    },
    {
     "expr": "(sum(${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\", return_code=\"NXDOMAIN\"}))*100 / sum(${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\"}) ",
     "legendFormat": "NXDOMAIN"
    },
    {
     "expr": "(sum(${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\", return_code!~\"NOERROR|NXDOMAIN\"}) )*100 / sum(${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\"})",
     "legendFormat": "REST"
    }
   ]
  },
  {
   "title": "Top Domains",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(${prom_prefix}_top_domains_total{job=~\"$job\", stream_id=~\"$stream_id\"}[$__interval]) != 0"
    }
   ]
  },
  {
   "title": "Top NX Domains",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(${prom_prefix}_top_nxdomains_total{job=~\"$job\", stream_id=~\"$stream_id\"}[$__interval]) != 0"
    }
   ]
  },
  {
   "title": "Top Clients",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(${prom_prefix}_top_requesters_total{job=~\"$job\", stream_id=~\"$stream_id\"}[$__interval]) != 0"
    }
   ]
  },
  {
   "title": "Top Qtypes",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "sum by(query_type) ( increase(${prom_prefix}_packets_count{job=~\"$job\", stream_id=~\"$stream_id\"}[$__interval]) ) != 0",
     "legendFormat": "{{ query_type }}"
    }
   ]
  }
 ]
}