{
 "title": "DnsCollector Prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"$job\"},instance)"
    }
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": {
     "query": "label_values({job=\"$job\"},stream)"
    }
   },
   {
    "name": "range",
    "label": "Range",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d"
   },
   { "name": "ip", "label": "IP", "query": ".*" },
   { "name": "domain", "label": "Domain", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Current queries per second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "repeat": "stream",
   "fieldConfig": { "defaults": { "unit": "q/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_qps{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}",
     "legendFormat": "{{ stream }}"
    }
   ]
  },
  {
   "title": "Total Clients",
   "type": "stat",
   "description": "Total Client IP",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_requesters_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}"
    }
   ]
  },
  {
   "title": "Number of Domain Names",
   "type": "stat",
   "description": "Total Domain",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_domains_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}"
    }
   ]
  },
  {
   "title": "Total Slow domains",
   "type": "stat",
   "description": "Total Slow domains",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_domains_slow_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}"
    }
   ]
  },
  {
   "title": "Received/sent data [24h]",
   "type": "stat",
   "description": "DNS data usage / day",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(dnscollector_received_bytes_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[1d]) + increase(dnscollector_sent_bytes_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[1d])"
    }
   ]
  },
  {
   "title": "Total DNS queries [24h]",
   "type": "stat",
   "description": "Total DNS queries over 1 day",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dnscollector_operations_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\", operation=~\".*_QUERY\"}[1d]))"
    }
   ]
  },
  {
   "title": "Maximum Qps",
   "type": "stat",
   "description": "Max queries/sec observed",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_qps_max_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}"
    }
   ]
  },
  {
   "title": "Total Suspicious IP",
   "type": "stat",
   "description": "Total Suspicious IP",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_requesters_suspicious_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}"
    }
   ]
  },
  {
   "title": "Number of Non-Existent Domain",
   "type": "stat",
   "description": "Total Number of Non-Existent domain names",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_domains_nx_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}"
    }
   ]
  },
  {
   "title": "Total Suspicious domains",
   "type": "stat",
   "description": "Total Suspicious domains",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_domains_suspicious_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}"
    }
   ]
  },
  {
   "title": "Received/sent data [7d]",
   "type": "stat",
   "description": "Total bandwidth consumed over 7 days",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(dnscollector_received_bytes_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[7d]) + increase(dnscollector_sent_bytes_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[7d])"
    }
   ]
  },
  {
   "title": "Total DNS queries [7d]",
   "type": "stat",
   "description": "Total DNS queries over 7 days",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dnscollector_operations_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\", operation=~\".*_QUERY\"}[7d]))"
    }
   ]
  },
  { "title": "Network level inspection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "PPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (instance)(dnscollector_pps{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
     "legendFormat": "pps"
    },
    {
     "expr": "sum by (instance)(rate(dnscollector_packets_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[1h]))",
     "legendFormat": "avg  over [1h]"
    },
    {
     "expr": "sum by (instance)(dnscollector_pps_max_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Total packet rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(increase(dnscollector_packets_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[5m]))",
     "legendFormat": "5-minute rate"
    }
   ]
  },
  {
   "title": "Received packets by IP  protocol",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ip)(dnscollector_ipproto_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Received packets by transport protocol",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (transport)(dnscollector_transports_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Bandwidth network traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(dnscollector_received_bytes_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[$range])",
     "legendFormat": "recv"
    },
    {
     "expr": "rate(dnscollector_sent_bytes_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[$range])*-1",
     "legendFormat": "trans"
    }
   ]
  },
  {
   "title": "Network packets [rate-$range]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dnscollector_transports_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[$range])) by (transport)",
     "legendFormat": "{{ transport }}"
    },
    {
     "expr": "sum(rate(dnscollector_ipproto_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[$range])) by (ip)",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Total hit by Client IP [Top 100]",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (ip)(dnscollector_requesters_top_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\", ip=~\"$ip\"})",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Client rate by IP [rate-$range]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(rate(dnscollector_requesters_top_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\", ip=~\"$ip\"}[$range])) by (ip))",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  { "title": "DNS level inspection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Total DNS operation",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation)(dnscollector_operations_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Packet by operation [rate-$range]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(dnscollector_operations_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[$range])) by (operation)",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Total Queries by QType",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_qtypes_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}",
     "legendFormat": "{{qtype}}"
    }
   ]
  },
  {
   "title": "Packet by Qtype [rate-$range]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 57 },
   "targets": [
    {
     "expr": "sum(rate(dnscollector_qtypes_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[$range])) by (qtype)",
     "legendFormat": "{{ qtype }}"
    }
   ]
  },
  {
   "title": "Total Replies by return code",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_rcodes_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}",
     "legendFormat": "{{ rcode }}"
    }
   ]
  },
  {
   "title": "Packet by Qtype [rate-$range]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(dnscollector_rcodes_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[$range])) by (rcode)",
     "legendFormat": "{{ rcode }}"
    }
   ]
  },
  {
   "title": "Queries length",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_query_len_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}",
     "legendFormat": "{{ length }}"
    }
   ]
  },
  {
   "title": "Minimum",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(dnscollector_query_len_min_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Queries by size [rate-$range]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 77 },
   "targets": [
    {
     "expr": "sum(rate(dnscollector_query_len_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[$range])) by (length)",
     "legendFormat": "{{ length }}"
    }
   ]
  },
  {
   "title": "Maximum",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(dnscollector_query_len_max_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Replies length",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_reply_len_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}",
     "legendFormat": "{{ length }}"
    }
   ]
  },
  {
   "title": "Minimum",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(dnscollector_reply_len_min_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Replies by size [rate-$range]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 87 },
   "targets": [
    {
     "expr": "sum(rate(dnscollector_reply_len_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[$range])) by (length)",
     "legendFormat": "{{ length }}"
    }
   ]
  },
  {
   "title": "Maximum",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(dnscollector_reply_len_max_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "DNS Latency analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Total response time",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (latency)(dnscollector_latency_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
     "legendFormat": "{{ latency }}"
    }
   ]
  },
  {
   "title": "Minimum",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(dnscollector_latency_min_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Response time [rate-$range]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 98 },
   "targets": [
    {
     "expr": "sum(rate(dnscollector_latency_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[$range])) by (latency)",
     "legendFormat": "{{ latency }}"
    }
   ]
  },
  {
   "title": "Maximum",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(dnscollector_latency_max_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Total slow domain  [Top 100 ]",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "sum by (domain)(dnscollector_domains_slow_top_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\", domain=~\"$domain\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "First level domain analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 },
   "collapsed": true,
   "panels": [
    {
     "title": "TLD repartition",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (domain)(dnscollector_firstleveldomains_top_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
       "legendFormat": "{{ domain }}"
      }
     ]
    },
    {
     "title": "Most popular first level domains queried",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum by (domain)(dnscollector_firstleveldomains_top_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\", domain=~\"$domain\"})",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Hit by NOERROR [Top 20] [rate-$range]",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20,sum(rate(dnscollector_firstleveldomains_top_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\", domain=~\"$domain\"}[$range])) by (domain))",
       "legendFormat": "{{ domain }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Full domain names analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 },
   "collapsed": true,
   "panels": [
    {
     "title": "Most popular domains queried",
     "type": "table",
     "gridPos": { "h": 17, "w": 11, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by (domain)(dnscollector_domains_top_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\", domain=~\"$domain\"})",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "New domains rate",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 13, "x": 11, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance)(increase(dnscollector_domains_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[5m]))",
       "legendFormat": "5-minute rate "
      }
     ]
    },
    {
     "title": "Domains repartition",
     "type": "piechart",
     "gridPos": { "h": 17, "w": 11, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(20,sum by (domain)(dnscollector_domains_top_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}))",
       "legendFormat": "{{ domain }}"
      }
     ]
    },
    {
     "title": "Hit by NOERROR [Top 20] [rate-$range]",
     "type": "graph",
     "gridPos": { "h": 17, "w": 13, "x": 11, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20,sum(rate(dnscollector_domains_top_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\", domain=~\"$domain\"}[$range])) by (domain))",
       "legendFormat": "{{ domain }}"
      }
     ]
    },
    {
     "title": "Most popular NXDOMAIN queried",
     "type": "table",
     "gridPos": { "h": 14, "w": 11, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum by (domain)(dnscollector_domains_nx_top_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\", domain=~\"$domain\"})",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "NXDOMAIN rate",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 13, "x": 11, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance)(increase(dnscollector_domains_nx_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[5m]))",
       "legendFormat": "5-minute rate "
      }
     ]
    },
    {
     "title": "Domain length repartition",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (length)(dnscollector_qname_len_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
       "legendFormat": "{{ length }}"
      }
     ]
    },
    {
     "title": "Minimum Length",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (instance)(dnscollector_qname_len_min_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
       "legendFormat": "Min"
      }
     ]
    },
    {
     "title": "Length [rate-$range]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 61 },
     "targets": [
      {
       "expr": "sum(rate(dnscollector_qname_len_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[$range])) by (length)",
       "legendFormat": "{{ length }}"
      }
     ]
    },
    {
     "title": "Maximum Length",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (instance)(dnscollector_qname_len_max_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"})",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Suspicious behaviour",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total hit by IP [Top 100 ]",
     "type": "table",
     "gridPos": { "h": 15, "w": 8, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum by (ip)(dnscollector_requesters_suspicious_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\", ip=~\"$ip\"})",
       "legendFormat": "{{ ip }}"
      }
     ]
    },
    {
     "title": "Client packet by IP [rate-$range]",
     "type": "graph",
     "gridPos": { "h": 15, "w": 16, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20,sum(rate(dnscollector_requesters_suspicious_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\"}[$range])) by (ip))",
       "legendFormat": "{{ip}}"
      }
     ]
    },
    {
     "title": "Total suspicious domain [Top 100 ]",
     "type": "table",
     "gridPos": { "h": 13, "w": 11, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum by (domain)(dnscollector_domains_suspicious_top_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\", domain=~\"$domain\"})",
       "legendFormat": "{{domain}}"
      }
     ]
    },
    {
     "title": "Hit by suspicious domain [Top 20] [rate-$range]",
     "type": "graph",
     "gridPos": { "h": 13, "w": 13, "x": 11, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20,sum(rate(dnscollector_domains_suspicious_top_total{job=~\"$job\",instance=~\"$instance\",stream=~\"$stream\", domain=~\"$domain\"}[$range])) by (domain))",
       "legendFormat": "{{ domain }}"
      }
     ]
    }
   ]
  }
 ]
}