{
 "title": "dnscollector-v6",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "logger", "query": { "query": "label_values(job)" } },
   { "name": "stream", "query": { "query": "label_values(stream)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_pps{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "rate(dnscollector_packets{job=~\"$logger\",stream=~\"$stream\"}[1h])",
     "legendFormat": "Average over [1h]"
    },
    {
     "expr": "dnscollector_pps_max{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "PPS  history",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "dnscollector_pps{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "pps"
    }
   ]
  },
  {
   "title": "Incoming Packets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_packets_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Incoming packet rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "increase(dnscollector_packets_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "5-minute rate"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "dnscollector_operations_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 5, "y": 17 },
   "targets": [
    {
     "expr": "increase(dnscollector_operations_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "dnscollector_transports_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{transport}}"
    },
    {
     "expr": "dnscollector_ipproto_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 5, "y": 24 },
   "targets": [
    {
     "expr": "increase(dnscollector_transports_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "{{transport}}"
    },
    {
     "expr": "increase(dnscollector_ipproto_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Total Requesters",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_requesters_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 32 },
   "targets": [
    {
     "expr": "dnscollector_requesters_top_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "New clients rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "increase(dnscollector_requesters_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "5-minute rate "
    }
   ]
  },
  {
   "title": "Total Domains",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_domains_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 41 },
   "targets": [
    {
     "expr": "dnscollector_domains_top_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "New domains rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "increase(dnscollector_domains_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "5-minute rate "
    }
   ]
  },
  {
   "title": "Total Non-Existent Domains",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_domains_nx_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 50 },
   "targets": [
    {
     "expr": "dnscollector_domains_nx_top_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "New NXDOMAIN rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "increase(dnscollector_domains_nx_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "5-minute rate "
    }
   ]
  },
  {
   "title": "Total Slow Domains",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_domains_slow_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 59 },
   "targets": [
    {
     "expr": "dnscollector_domains_slow_top_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Slow domain rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "increase(dnscollector_domains_slow_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "5-minute rate "
    }
   ]
  },
  {
   "title": "Total Suspicious Domains",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_domains_suspicious_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 69 },
   "targets": [
    {
     "expr": "dnscollector_domains_suspicious_top_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Suspicious domain rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "increase(dnscollector_domains_suspicious_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "5-minute rate "
    }
   ]
  },
  {
   "title": "Query types",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_qtypes_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{qtype}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 9, "y": 79 },
   "targets": [
    {
     "expr": "increase(dnscollector_qtypes_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "{{qtype}}"
    }
   ]
  },
  {
   "title": "Response codes",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_rcodes_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 9, "y": 89 },
   "targets": [
    {
     "expr": "increase(dnscollector_rcodes_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_latency_min_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "dnscollector_latency_max_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 3, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_latency_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{latency}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 9, "y": 99 },
   "targets": [
    {
     "expr": "increase(dnscollector_latency_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "{{latency}}"
    }
   ]
  },
  {
   "title": "Qname Length",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_qname_len_min_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "dnscollector_qname_len_max_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Qname size repartition",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 3, "y": 110 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_qname_len_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{length}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 9, "y": 110 },
   "targets": [
    {
     "expr": "increase(dnscollector_qname_len_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "{{length}}"
    }
   ]
  },
  {
   "title": "Query Length",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_query_len_min_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "dnscollector_query_len_max_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Queries length repartition",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 3, "y": 122 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_query_len_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{length}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 9, "y": 122 },
   "targets": [
    {
     "expr": "increase(dnscollector_query_len_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "{{length}}"
    }
   ]
  },
  {
   "title": "Reply Length",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_reply_len_min_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "dnscollector_reply_len_max_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Replies length repartition",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 3, "y": 134 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnscollector_reply_len_total{job=~\"$logger\",stream=~\"$stream\"}",
     "legendFormat": "{{length}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 9, "y": 134 },
   "targets": [
    {
     "expr": "increase(dnscollector_reply_len_total{job=~\"$logger\",stream=~\"$stream\"}[5m])",
     "legendFormat": "{{length}}"
    }
   ]
  }
 ]
}